SELECT * FROM tab;

SELECT 
	FIRST_NAME || ' ' || LAST_NAME  name , d.DEPARTMENT_NAME  deptname, l.CITY city 
FROM 
	EMPLOYEES e , DEPARTMENTS d, LOCATIONS l  
WHERE 
	e.DEPARTMENT_ID  = d.DEPARTMENT_ID 
	AND 
	d.LOCATION_ID  = l.LOCATION_ID ;